const cities = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Toronto",
  "Montreal",
  "Vancouver",
  "Mexico City",
  "Sao Paulo",
  "Rio de Janeiro",
  "Buenos Aires",
  "Bogota",
  "Lima",
  "Santiago",
  "London",
  "Paris",
  "Madrid",
  "Barcelona",
  "Rome",
  "Milan",
  "Berlin",
  "Munich",
  "Amsterdam",
  "Brussels",
  "Vienna",
  "Zurich",
  "Stockholm",
  "Copenhagen",
  "Oslo",
  "Helsinki",
  "Dublin",
  "Lisbon",
  "Athens",
  "Istanbul",
  "Moscow",
  "St. Petersburg",
  "Prague",
  "Warsaw",
  "Budapest",
  "Bucharest",
  "Kiev",
  "Minsk",
  "Sofia",
  "Belgrade",
  "Zagreb",
  "Sarajevo",
  "Tirana",
  "Skopje",
  "Pristina",
  "Podgorica",
  "Cairo",
  "Cape Town",
  "Johannesburg",
  "Nairobi",
  "Lagos",
  "Accra",
  "Casablanca",
  "Tunis",
  "Algiers",
  "Dubai",
  "Abu Dhabi",
  "Riyadh",
  "Jeddah",
  "Tehran",
  "Baghdad",
  "Amman",
  "Beirut",
  "Damascus",
  "Jerusalem",
  "Tokyo",
  "Osaka",
  "Seoul",
  "Shanghai",
  "Beijing",
  "Hong Kong",
  "Taipei",
  "Singapore",
  "Bangkok",
  "Jakarta",
  "Manila",
  "Kuala Lumpur",
  "Ho Chi Minh City",
  "Hanoi",
  "Sydney",
  "Melbourne",
  "Brisbane",
  "Perth",
  "Auckland",
  "Wellington",
  "Christchurch",
  "Queenstown",
  "Honolulu",
  "San Juan",
  "Havana",
  "Port-au-Prince",
  "Santo Domingo",
  "Kingston",
  "Nassau",
  "Bridgetown",
  "Port of Spain",
  "Caracas",
  "Quito",
  "Guayaquil",
  "Manaus",
  "Brasilia",
  "Belo Horizonte",
  "Salvador",
  "Recife",
  "Fortaleza",
  "Curitiba",
  "Porto Alegre",
  "Montevideo",
  "Asuncion",
  "La Paz",
  "Santa Cruz de la Sierra",
  "Sucre",
  "Medellin",
  "Cali",
  "Barranquilla",
  "Cartagena",
  "Arequipa",
  "Trujillo",
  "Chiclayo",
  "Piura",
  "Iquitos",
  "Valparaiso",
  "Concepcion",
  "Antofagasta",
  "Vina del Mar",
  "Punta Arenas",
  "Montevideo",
  "Punta del Este",
  "Salto",
  "Paysandu",
  "Rivera",
  "Tacuarembo",
  "Melo",
  "Durazno",
  "Trinidad",
  "Artigas",
  "Carmelo",
  "Colonia del Sacramento",
  "Canelones",
  "Maldonado",
  "San Carlos",
  "Minas",
  "Treinta y Tres",
];

export const getRandomCity = () => {
  const randomIndex = Math.floor(Math.random() * cities.length);
  const randomCity = cities[randomIndex];
  console.log("Selected city:", randomCity);
  return randomCity;
};
